INSERT INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME) VALUES (1, 'CRICKET_BAT');
INSERT INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME) VALUES (2, 'BALL');
INSERT INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME) VALUES (3, 'HELMET');
INSERT INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME) VALUES (4, 'BATTING_GLOVES');

INSERT INTO WAREHOUSES (WAREHOUSE_ID, WAREHOUSE_NAME, POS_X, POS_Y) VALUES (1, 'HYDERABAD', 0, 0);
INSERT INTO WAREHOUSES (WAREHOUSE_ID, WAREHOUSE_NAME, POS_X, POS_Y) VALUES (2, 'CHENNAI', 200, -800);
INSERT INTO WAREHOUSES (WAREHOUSE_ID, WAREHOUSE_NAME, POS_X, POS_Y) VALUES (3, 'BENGALURU', -100, -600);
INSERT INTO WAREHOUSES (WAREHOUSE_ID, WAREHOUSE_NAME, POS_X, POS_Y) VALUES (4, 'MUMBAI', -800, 100);

INSERT INTO WAREHOUSE_PRODUCTS(WAREHOUSE_ID, PRODUCT_ID) VALUES (1, 1);
INSERT INTO WAREHOUSE_PRODUCTS(WAREHOUSE_ID, PRODUCT_ID) VALUES (2, 2);
INSERT INTO WAREHOUSE_PRODUCTS(WAREHOUSE_ID, PRODUCT_ID) VALUES (3, 3);
INSERT INTO WAREHOUSE_PRODUCTS(WAREHOUSE_ID, PRODUCT_ID) VALUES (4, 4);