CREATE TABLE PRODUCTS (
    PRODUCT_ID INTEGER AUTO_INCREMENT NOT NULL,
    PRODUCT_NAME VARCHAR(20) NOT NULL,
    PRIMARY KEY (PRODUCT_ID),
    CONSTRAINT PRDT_PRODUCT_NAME_UK	
    	UNIQUE (PRODUCT_NAME)
);

CREATE TABLE WAREHOUSES (
    WAREHOUSE_ID INTEGER AUTO_INCREMENT NOT NULL,
    WAREHOUSE_NAME VARCHAR(20) NOT NULL,
    POS_X INTEGER NOT NULL,
    POS_Y INTEGER NOT NULL,
    PRIMARY KEY (WAREHOUSE_ID),
    CONSTRAINT WRHS_WAREHOUSE_NAME_UK
    	UNIQUE (WAREHOUSE_NAME)
);

CREATE TABLE WAREHOUSE_PRODUCTS (
    WAREHOUSE_ID INTEGER NOT NULL,
    PRODUCT_ID INTEGER NOT NULL,
    PRIMARY KEY (WAREHOUSE_ID, PRODUCT_ID),
    CONSTRAINT WAPR_PRODUCT_ID_FK
    	FOREIGN KEY (PRODUCT_ID)
    		REFERENCES PRODUCTS (PRODUCT_ID),
    CONSTRAINT WAPR_WAREHOUSE_ID_FK
    	FOREIGN KEY (WAREHOUSE_ID)
    		REFERENCES WAREHOUSES (WAREHOUSE_ID)
);

CREATE TABLE CUSTOMERS (
    CUSTOMER_ID INTEGER AUTO_INCREMENT NOT NULL,
    CUSTOMER_NAME VARCHAR(20) NOT NULL,
    POS_X INTEGER NOT NULL,
    POS_Y INTEGER NOT NULL,
    PRIMARY KEY (CUSTOMER_ID),
    CONSTRAINT CUST_CUSTOMER_NAME_UK
    	UNIQUE (CUSTOMER_NAME)
);

CREATE TABLE DISTANCE_MAP (
    CUSTOMER_ID INTEGER NOT NULL,
    WAREHOUSE_ID INTEGER NOT NULL,
    DISTANCE INTEGER NOT NULL,
    PRIMARY KEY (CUSTOMER_ID, WAREHOUSE_ID),
    CONSTRAINT DIMA_WAREHOUSE_ID_FK
    	FOREIGN KEY (CUSTOMER_ID)
    		REFERENCES CUSTOMERS (CUSTOMER_ID),
    CONSTRAINT DIMA_PRODUCT_ID_FK
    	FOREIGN KEY (WAREHOUSE_ID)
    		REFERENCES WAREHOUSES (WAREHOUSE_ID)
);
